In [ ]:
import pandas as pd

df = pd.read_csv("ecommerce_dataset_updated.csv")

df.head()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3660 entries, 0 to 3659
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   User_ID           3660 non-null   object
 1   Product_ID        3660 non-null   object
 2   Category          3660 non-null   object
 3   Price (Rs.)       3660 non-null   float64
 4   Discount (%)      3660 non-null   int64
 5   Final_Price(Rs.)  3660 non-null   float64
 6   Payment_Method    3660 non-null   object
 7   Purchase_Date     3660 non-null   object
dtypes: float64(2), int64(1), object(5)
memory usage: 228.9+ KB

       Price (Rs.)  Discount (%)  Final_Price(Rs.)
count  3660.000000   3660.000000       3660.000000
mean    254.800675     18.825137        206.906579
std     141.682621     14.731338        122.687844
min      10.090000      0.000000          5.890000
25%     134.012500      5.000000        104.512500
50%     253.845000     15.000000        199.185000
75%     377.595000     25.000000        304.117500
max     499.960000     50.000000        496.820000

In [ ]:
df.isnull().sum()
df = df.dropna()  # or fill depending on column

In [ ]:
df = df.drop_duplicates()

In [ ]:
df.columns = df.columns.str.strip()
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(" ", "_")
df.columns = df.columns.str.replace(r"[()%\.]", "", regex=True)

print(df.columns)

Index(['user_id', 'product_id', 'category', 'price_rs', 'discount_',
       'final_pricers', 'payment_method', 'purchase_date'],
      dtype='object')

In [ ]:
df['revenue'] = df['final_pricers']

In [ ]:
df['discount_value'] = df['price_rs'] - df['final_pricers']

In [ ]:
df['purchase_date'] = pd.to_datetime(df['purchase_date'], dayfirst=True)

In [ ]:
df['month'] = df['purchase_date'].dt.month
df['year'] = df['purchase_date'].dt.year

In [ ]:
df.head()

,user_id,product_id,category,price_rs,discount_,final_pricers,payment_method,purchase_date,revenue,discount_value,month,year
0,337c166f,f414122f-e,Sports,36.53,15,31.05,Net Banking,2024-11-12,31.05,5.48,11,2024
1,d38a19bf,fde50f9c-5,Clothing,232.79,20,186.23,Net Banking,2024-02-09,186.23,46.56,2,2024
2,d7f5f0b0,0d96fc90-3,Sports,317.02,25,237.76,Credit Card,2024-09-01,237.76,79.26,9,2024
3,395d4994,964fc44b-d,Toys,173.19,25,129.89,UPI,2024-04-01,129.89,43.30,4,2024
4,a83c145c,d70e2fc6-e,Beauty,244.80,20,195.84,Net Banking,2024-09-27,195.84,48.96,9,2024

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3660 entries, 0 to 3659
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   user_id         3660 non-null   object
 1   product_id      3660 non-null   object
 2   category        3660 non-null   object
 3   price_rs        3660 non-null   float64
 4   discount_       3660 non-null   int64
 5   final_pricers   3660 non-null   float64
 6   payment_method  3660 non-null   object
 7   purchase_date   3660 non-null   datetime64[ns]
 8   revenue         3660 non-null   float64
 9   discount_value  3660 non-null   float64
 10  month           3660 non-null   int32
 11  year            3660 non-null   int32
dtypes: datetime64[ns](1), float64(4), int32(2), int64(1), object(4)
memory usage: 314.7+ KB

In [ ]:
df.to_csv("cleaned_ecommerce.csv", index=False)